<template>
  <div class="d-flex justify-content-center" style="margin-top: 20px">
    <button class="btn btn-primary mx-2" @click="updateChart7">7D</button>
    <button class="btn btn-primary mx-2" @click="updateChart30">30D</button>
    <button class="btn btn-primary mx-2" @click="updateChart90">90D</button>
  </div>
  <div class="d-flex justify-content-center" style="margin-top: 20px">
    <apexchart
      ref="radar"
      width="550"
      type="line"
      :options="chartOptions"
      :series="series"
    ></apexchart>
  </div>
</template>
<script>
export default {
  data: function () {
    return {
      chartOptions: {
        chart: {
          id: "vuechart-example",
          toolbar: {
            show: true,
            tools: {
              download: true,
              selection: false,
              zoom: false,
              zoomin: false,
              zoomout: false,
              pan: false,
              reset: false | '<img src="/static/icons/reset.png" width="20">',
            },
          },
        },
        title: {
          text: "Ethereums price movement",
          align: "left",
        },
        xaxis: {
          type: "datetime",
          categories: [
            "13 Nov",
            "14 Nov",
            "15 Nov",
            "16 Nov",
            "17 Nov",
            "18 Nov",
            "19 Nov",
          ],
        },
      },
      series: [
        {
          name: "Ethereum",
          data: [0.95, 1.1, 1.2, 1, 1.1, 1.4, 1],
        },
      ],
      yaxis: {
        title: {
          text: "Price, $",
        },
      },
    };
  },
  methods: {
    updateChart7() {
      const newData = [0.95, 1.1, 1.2, 1, 1.1, 1.4, 1, 0.9];
      this.$refs.radar.updateOptions({
        xaxis: {
          categories: [
            "13 Nov",
            "14 Nov",
            "15 Nov",
            "16 Nov",
            "17 Nov",
            "18 Nov",
            "19 Nov",
          ],
        },
      });
      this.series = [
        {
          data: newData,
        },
      ];
    },
    updateChart30() {
      const newData = [
        0.95, 1.1, 1.2, 1, 1.1, 1.4, 1, 0.9, 0.95, 1.1, 1.2, 1, 1.1, 1.4, 1,
        0.9, 0.95, 1.1, 1.2, 1, 1.1, 1.4, 1, 0.9, 0.95, 1.1, 1, 0.9, 1.1, 1.2,
      ];
      this.$refs.radar.updateOptions({
        xaxis: {
          categories: [
            "20 Oct",
            "21 Oct",
            "22 Oct",
            "23 Oct",
            "24 Oct",
            "25 Oct",
            "26 Oct",
            "27 Oct",
            "28 Oct",
            "29 Oct",
            "30 Oct",
            "31 Oct",
            "01 Nov",
            "02 Nov",
            "03 Nov",
            "04 Nov",
            "05 Nov",
            "06 Nov",
            "07 Nov",
            "08 Nov",
            "09 Nov",
            "10 Nov",
            "11 Nov",
            "12 Nov",
            "13 Nov",
            "14 Nov",
            "15 Nov",
            "16 Nov",
            "17 Nov",
            "18 Nov",
            "19 Nov",
          ],
        },
      });
      this.series = [
        {
          data: newData,
        },
      ];
    },
    updateChart90() {
      const newData = [
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1,
        0.9,
        1.1,
        1.2,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1,
        0.9,
        1.1,
        1.2,
        ,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1.2,
        1,
        1.1,
        1.4,
        1,
        0.9,
        0.95,
        1.1,
        1,
        0.9,
        1.1,
        1.8,
      ];
      this.$refs.radar.updateOptions({
        xaxis: {
          categories: [
            "21 Aug",
            "22 Aug",
            "23 Aug",
            "24 Aug",
            "25 Aug",
            "26 Aug",
            "27 Aug",
            "28 Aug",
            "29 Aug",
            "30 Aug",
            "31 Aug",
            "01 Sep",
            "02 Sep",
            "03 Sep",
            "04 Sep",
            "05 Sep",
            "06 Sep",
            "07 Sep",
            "08 Sep",
            "09 Sep",
            "10 Sep",
            "11 Sep",
            "12 Sep",
            "13 Sep",
            "14 Sep",
            "15 Sep",
            "16 Sep",
            "17 Sep",
            "18 Sep",
            "19 Sep",
            "20 Sep",
            "21 Sep",
            "22 Sep",
            "23 Sep",
            "24 Sep",
            "25 Sep",
            "26 Sep",
            "27 Sep",
            "28 Sep",
            "29 Sep",
            "30 Sep",
            "01 Oct",
            "02 Oct",
            "03 Oct",
            "04 Oct",
            "05 Oct",
            "06 Oct",
            "07 Oct",
            "08 Oct",
            "09 Oct",
            "10 Oct",
            "11 Oct",
            "12 Oct",
            "13 Oct",
            "14 Oct",
            "15 Oct",
            "16 Oct",
            "17 Oct",
            "18 Oct",
            "19 Oct",
            "20 Oct",
            "21 Oct",
            "22 Oct",
            "23 Oct",
            "24 Oct",
            "25 Oct",
            "26 Oct",
            "27 Oct",
            "28 Oct",
            "29 Oct",
            "30 Oct",
            "31 Oct",
            "01 Nov",
            "02 Nov",
            "03 Nov",
            "04 Nov",
            "05 Nov",
            "06 Nov",
            "07 Nov",
            "08 Nov",
            "09 Nov",
            "10 Nov",
            "11 Nov",
            "12 Nov",
            "13 Nov",
            "14 Nov",
            "15 Nov",
            "16 Nov",
            "17 Nov",
            "18 Nov",
            "19 Nov",
          ],
        },
      });
      this.series = [
        {
          data: newData,
        },
      ];
    },
  },
};
</script>
